config/routes.rb
Rails.application.routes.draw do

  get '/' => 'site#home'
  get '/contact' => 'site#contact'
  resources :projects do 
    resources :entries
  end

end

app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :project
	validates :hours, numericality: {only_integer: true}, presence: true
	validates :minutes, numericality: {only_integer: true}, presence: true
	validates :date, presence: true
	validates :project_id, numericality: {only_integer: true}, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
has_many :entries
 
 	validates :name, uniqueness: true, presence: true, length: {maximum:30}


	def self.show_all
		projects = Project.all
		
	end
	def self.last_created(n)
		return Project.order(:created_at => :asc).limit(n)
	end

	def self.clean_old
		projects = Project.where("created_at < ?", Date.today - 1.week).destroy_all

	end


	def total_hours_in_month(month, year)
		start_date = DateTime.new(year, month, 1)
		end_date = DateTime.new(year, month + 1, 1)
		entries = self.entries.where("date > ?",start_date).where(" date < ? ",end_date)
		hours = entries.reduce(0) {|sym, entry| sym + entry.hours}
		
		
	end

	def total_minutes_in_month(month, year)
		start_date = DateTime.new(year, month, 1)
		end_date = DateTime.new(year, month + 1, 1)
		entries = self.entries.where("date > ?",start_date).where(" date < ? ",end_date)
		
		minutes = entries.reduce(0) {|sym, entry| sym + entry.minutes}
		
	end

	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	
	
	def new 
		@project = Project.find(params[:project_id])
		@entry = @project.entries.new
		render "new"
	end

	def edit 
		@project = Project.find(params[:project_id])
		@entry = @project.entries.find(params[:id])
		render "edit"
	end

	def update
		
		@entry = Entry.find(params[:id])

		if @entry.update_attributes(entry_params)
			flash[:notice] = "Updated!"
			redirect_to action: 'index'
		else
			render 'edit'
		end


	end

	def destroy
		
		@entry = Entry.find(params[:id])
		@entry.destroy
		flash[:alert] = "DELETED!"
		redirect_to(project_entries_path)
	end



	def index
		@project = Project.find(params[:project_id])
		@entries = @project.entries
		

		render 'index'
	end

	def create
		@project = Project.find(params[:project_id])
		@entry = @project.entries.new(entry_params)

		if @entry.save 
			flash[:notice] = "Added new entry!"
			redirect_to action: 'index', controller: 'entries', project_id: @project.id
		else 
			flash[:alert] = "Creation Failed."
			render 'new'
		end
	end

	private 
	def entry_params
		params.require(:entry).permit(:hours, :minutes, :date, :comment)
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController




	def index
		@projects = Project.last_created(10)		
		render('index')
	end
	def show

		@project = Project.find_by(:id => params[:id])
		if @project.nil? 
			render( :status => 404)
		else
			render 'show'
		end
	end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController


	def home 
		render 'home'
	end
	def contact
		render 'contact'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def pretty_date(date)
		return date.strftime("%B %-d, %Y")
	end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/entries/_form.html.erb
<div class="jumbotron">
	<div class="pager-header text-center">
		<h1>JUMBOTRON</h1>
	</div>
</div>

app/views/entries/edit.html.erb
<h1>
	Edit Entry for 
	<%= @project.name %>

</h1>

	 	<% if flash[:alert] %>
			<div class="alert alert-danger" role="alert">
	  	<%= flash[:alert] %> 
	 		</div>
		<% end %> 

	<% if @entry.errors.any? %>
	<ul>
		<% @entry.errors.full_messages.each do |error| %>
		<li> <%= error%></li>
		<% end%>
	</ul>
	<%end%>
	<% if @entry.errors.any? %>
	<ul>
		<% @entry.errors.full_messages.each do |error| %>
		<li> <%= error%></li>
		<% end%>
	</ul>
	<%end%>
<div class="form-group has-validation">
	
	<%= form_for([@project, @entry]) do |f| %>
		<%= f.label :hours %> 
		<br>
		<%= f.text_field :hours %>
		
		<br>
		<%= f.label :minutes %> 
		<br>
		<%= f.text_field :minutes %>
		
		<br>
		<%= f.label :date %> 
		<br>
		<%= f.date_field :date %>
		
		<br>
		
		<%= f.label :comment %> 
		<br>
		<%= f.text_field :comment %>
		
		<br>
		<br>

		<button class= "btn btn-default btn-lg"type="submit">Edit Entry</button>
	<% end%>
	</div>

app/views/entries/index.html.erb
<h1 style="text-align: center;">Entries Index</h1>
<h3>Project Name - <%= @project.name %></h3>
<%= render('form') %>
<% if flash[:notice] %> 
<div class="alert alert-success" role="alert">
  <%= flash[:notice] %> 
  </div>
  <% end %> 
  <% if flash[:alert] %> 
<div class="alert alert-danger" role="alert">
  <%= flash[:alert] %> 
  </div>
<% end %> 


<ul class="list-group">
	<% @entries.each do |entry| %>
	<li  class="list-group-item">
		<a href="<%= edit_project_entry_path(@project, entry)%>"><%= entry.comment %></a> -
		 Hours: <%= entry.hours %>
		 Minutes: <%= entry.minutes %>
		 <!-- Date --> <%= pretty_date(entry.date) %>
		<button class= "btn btn-danger btn-xs pull-right">
		<%= link_to('Delete', project_entry_path(@project, entry), :method => :delete, :data => {confirm: 'Are you sure?'}) %>
		</button>
	</li>
	<% end%>
</ul>

<a href="/projects/<%= @project.id%>/entries/new">Add new entry</a>
<br>
<a href="<%= projects_path %>">Back to projects index</a>

app/views/entries/new.html.erb
<div class="page-header">
	<h1>
		New Entry for 
		<%= @project.name %>

	</h1>
</div>
	 	<% if flash[:alert] %>
			<div class="alert alert-danger" role="alert">
	  	<%= flash[:alert] %> 
	 		</div>
		<% end %> 

	<% if @entry.errors.any? %>
	<ul>
		<% @entry.errors.full_messages.each do |error| %>
		<li> <%= error%></li>
		<% end%>
	</ul>
	<%end%>
<div class="form-group has-validation">
	
	<%= form_for([@project, @entry]) do |f| %>
		<%= f.label :hours %> 
		<br>
		<%= f.text_field :hours %>
		
		<br>
		<%= f.label :minutes %> 
		<br>
		<%= f.text_field :minutes %>
		
		<br>
		<%= f.label :date %> 
		<br>
		<%= f.date_field :date %>
		
		<br>
		
		<%= f.label :comment %> 
		<br>
		<%= f.text_field :comment %>
		
		<br>
		<br>

		<button class= "btn btn-default btn-lg"type="submit">Create New Entry</button>
	<% end%>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracking</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>

<body style="background-color: lightgrey;">
	<div class="container-fluid">
		
				

						<div class="col-lg-3 col-md-2 col-sm-2 col-xs-1"></div>

						<div class="col-lg-6 col-md-8 col-sm-8 col-xs-10">
							<div class="panel panel-default">
  								<div class="panel-body">
							<%= yield %>
								</div>
							</div>
						</div>
					
						<div class="col-lg-3 col-md-2 col-sm-2 col-xs-1">
						</div>
		
	</div>
</body>
</html>

app/views/projects/index.html.erb
<div class="page-header">
	<h1 style="text-align: center;">Projects</h1>
</div>



	<% @projects.each do |prj|%>
	<label> Project ID :<%= prj.id %> </label>
		<ul class="list-group">
			<li class="list-group-item"> 
				<a href= "<%=project_entries_path(prj)%>"><%= prj.name %></a>
				
				<%if prj.description.present? %>
				-
					<%= prj.description %> 
				<% end %>	
			</li>
			
		</ul>
				 <% end %>
		
	
		

app/views/projects/show.html.erb
<h1>Show a project</h1>

<div>
	<%= @project.name%>
	-
	<%= @project.description%>
	<br>
	
	Created at:
	<%= @project.created_at%>
	<br>
	Updated at :
	<%= @project.updated_at%>
</div>

app/views/site/about.html.erb
<h1>Contact us:</h1>
<p>kaykayyali@gmail.com</p>

app/views/site/contact.html.erb
<h1>Contact us:</h1>
<p>kaykayyali@gmail.com</p>

app/views/site/home.html.erb
<h1>Welcome to this timetracking tool</h1>
<p>Ironhack powered</p>